SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[test] 
as
SELECT	CLIENT_ID,'HO'c1,CASE	WHEN UNPI.EXCHANGE='ALL_EXCHANGES' THEN 17 
						    WHEN UNPI.EXCHANGE='NSE_BSE_EQUITY' THEN 34 
							WHEN UNPI.EXCHANGE='NSE_BSE_COMBINE' THEN 35
							WHEN UNPI.EXCHANGE='NSE_DERIVATIVES' THEN 4
							WHEN UNPI.EXCHANGE='COMMODITIES' THEN 16 
					  END segment,
		CASE WHEN CLIENT_ID IN ('1B29','1S50','1V10','1V20','1V39') 
			 THEN CASE WHEN CONVERT(NUMERIC(18,2),UNPI.LIMIT) <0 THEN 
							-1*CONVERT(NUMERIC(18,2),UNPI.LIMIT)+1000000 
				       ELSE 1000000 END
			 ELSE CONVERT(NUMERIC(18,2),UNPI.LIMIT) END limit
FROM	RMSTABLE_V5 P 
UNPIVOT (LIMIT FOR EXCHANGE IN(COMMODITIES,ALL_EXCHANGES,NSE_BSE_EQUITY,NSE_BSE_COMBINE,NSE_DERIVATIVES))AS UNPI 
GO
