SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE view  [dbo].[NONINTERNET_CLIENT_TRADING_PLATFORM]
AS


SELECT	CLIENT_ID,STUFF((SELECT ',' + COMPANY_CODE  FROM 
						(
							SELECT	DISTINCT C.CLIENT_ID,CASE WHEN C.COMPANY_CODE LIKE 'NSE_CASH' THEN 'NSE'
															  WHEN C.COMPANY_CODE LIKE 'NSE_FNO' THEN 'NSEFO'
															  WHEN C.COMPANY_CODE LIKE 'BSE_CASH' THEN 'BSE'	
															  WHEN C.COMPANY_CODE LIKE 'BSE_FNO' THEN 'BSEFO'
															  WHEN C.COMPANY_CODE LIKE 'CD_MCX' THEN 'CDMCX'	
															  WHEN C.COMPANY_CODE LIKE 'CD_NSE' THEN 'CDNSE'	
															   ELSE C.COMPANY_CODE
									END COMPANY_CODE
									,'Y' FLAG
							FROM	CAPSFO.DBO.CLIENT_MASTER C JOIN  CAPSFO.DBO.BROKERAGE_APPLY BA
							ON		C.COMPANY_CODE=BA.COMPANY_CODE AND C.CLIENT_ID=BA.CLIENT_ID
							WHERE	ACTIVE_INACTIVE='A' AND C.CLIENT_ID NOT IN ('11','502','TMID')
									AND DATEADD(D,0,DATEDIFF(D,0,C.REGISTRATION_DATE)) = DATEADD(D,0,DATEDIFF(D,0,GETDATE())) 
									/*OR C.LAST_MODIFIED_DATE > DATEADD(D,0,DATEDIFF(D,0,GETDATE()-2))*/
							GROUP BY C.CLIENT_ID,C.COMPANY_CODE,BRANCH_CODE 
							HAVING BRANCH_CODE<>'INTERNET'
						)A WHERE A.CLIENT_ID = B.CLIENT_ID  FOR XML PATH('')),1,1,'') COMPANY
FROM
(
	SELECT	DISTINCT C.CLIENT_ID,C.COMPANY_CODE,'Y' FLAG
	FROM	CAPSFO.DBO.CLIENT_MASTER C JOIN  CAPSFO.DBO.BROKERAGE_APPLY BA
	ON		C.COMPANY_CODE=BA.COMPANY_CODE AND C.CLIENT_ID=BA.CLIENT_ID
	WHERE	ACTIVE_INACTIVE='A' 
			AND DATEADD(D,0,DATEDIFF(D,0,C.REGISTRATION_DATE)) = DATEADD(D,0,DATEDIFF(D,0,GETDATE())) 
			OR C.LAST_MODIFIED_DATE > DATEADD(D,0,DATEDIFF(D,0,GETDATE()-2))
	GROUP BY C.CLIENT_ID,C.COMPANY_CODE,BRANCH_CODE 
	HAVING BRANCH_CODE<>'INTERNET'
) B GROUP BY CLIENT_ID 
GO
