SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VIEW_TRADING_TERMINAL]
AS

SELECT CLIENT_ID,CASE WHEN COMMODITY IS NULL  THEN 'NOW'
			  ELSE CASE WHEN FIN IS NULL THEN 'NEST'
			  	   ELSE CASE WHEN DAYS_DIFF_FIN_COMMODITY <= 3 THEN 'NEST'
						ELSE CASE WHEN SERIAL_NO IS NULL OR LEN(SERIAL_NO)=0	THEN 'NOWNEST' ELSE SERIAL_NO END								  
	  			   END
			  END
		 END TRADING_TERMINAL
FROM
(
	SELECT DISTINCT C.*,SERIAL_NO FROM
	(	
		SELECT	*,DATEADD(D,0,DATEDIFF(D,0,GETDATE()))CURRENTDATE,ABS(DATEDIFF(DAY,COMMODITY,FIN))DAYS_DIFF_FIN_COMMODITY				
		FROM
		(
		SELECT	DISTINCT C.CLIENT_ID,CASE WHEN C.COMPANY_CODE IN ('MCX','NCDEX') THEN 'COMMODITY' ELSE 'FIN' END COMPANY_CODE,
				MIN(DATEADD(D,0,DATEDIFF(D,7,REGISTRATION_DATE)))REGISTRATION_DATE
		FROM	CAPSFO.DBO.CLIENT_MASTER C JOIN  CAPSFO.DBO.BROKERAGE_APPLY BA
		ON		C.COMPANY_CODE=BA.COMPANY_CODE AND C.CLIENT_ID=BA.CLIENT_ID
		WHERE	ACTIVE_INACTIVE='A' AND BRANCH_CODE='INTERNET'
		GROUP BY C.CLIENT_ID,CASE WHEN C.COMPANY_CODE IN ('MCX','NCDEX') THEN 'COMMODITY' ELSE 'FIN' END 
		)X
		PIVOT	(MIN(REGISTRATION_DATE) FOR COMPANY_CODE IN ([COMMODITY],[FIN]))AS AV
	)C LEFT OUTER JOIN CAPSFO.DBO.CLIENT_DETAILS CD ON C.CLIENT_ID=CD.CLIENT_ID
)X 
GO
