SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE view [dbo].[activeClient]
as
SELECT  DISTINCT CLIENT_ID,(CASE WHEN COMPANY_CODE = 'JJSB' THEN 'BSE_CASH' ELSE COMPANY_CODE END)COMPANY_CODE FROM CAPSFO.DBO.CLIENTDETAILVIEW WITH (NOLOCK)
					WHERE CLIENT_ID IN
							(
								SELECT  CLIENT_CODE FROM CAPSFO.DBO.SOH
								UNION ALL
								SELECT	  A.CLIENT_ID
								FROM	CAPSFO.DBO.BEN_TRANSACTIONS A 
								WHERE	 A.CLIENT_ID NOT IN (SELECT DISTINCT CLIENT_ID FROM CAPSFO.DBO.IO_DP_MASTER WHERE CLIENT_NATURE = 'B')
								GROUP BY   A.CLIENT_ID,  A.ISIN HAVING SUM(PAYMENT_QTY - RECEIPT_QTY) > 0
								UNION ALL
								SELECT  CLIENT_ID FROM CAPSFO.DBO.TRADE1      
								WHERE  TRADE_DATE  >= CONVERT(DATETIME,GETDATE()-365,103)       
								UNION ALL
								SELECT  CLIENT_ID FROM  CAPSFO.DBO.CLIENT_MASTER 
								WHERE  REGISTRATION_DATE >= CONVERT(DATETIME,GETDATE()-365,103)
								union ALL
								select  ACCOUNTCODE from CAPSFO.DBO.FA_DATEWISE_AMT where VOUCHERDATE >= getdate()-365 and AMOUNT<>0
			           	)


GO
